version: 2
updates:
  # Configuration for Gradle (Java)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "[gradle]"
    labels:
      - "dependencies"
      - "java"
      - "automerge"
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: "increase"
    milestone: 1
    open-pull-requests-limit: 20
    rebase-strategy: "auto"
